server.port=8080

spring.application.name=tolunity

spring.datasource.url=jdbc:mysql://localhost:3306/tolunity?useSSL=false&serverTimezone=UTC
spring.datasource.username=shiwans
spring.datasource.password=shiwans123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
